\hypertarget{classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest}{\section{\-Catch\-Cxx\-Exceptions\-Test \-Class \-Reference}
\label{d4/d31/classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest}\index{\-Catch\-Cxx\-Exceptions\-Test@{\-Catch\-Cxx\-Exceptions\-Test}}
}
\subsection*{\-Public \-Member \-Functions}
\begin{DoxyCompactItemize}
\item 
def \hyperlink{classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest_a5a885e791aafe476fdd5c27e892d03aa}{test\-Catches\-Cxx\-Exceptions\-In\-Fixture\-Constructor}
\item 
def \hyperlink{classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest_a39d0315d69750ddc3d777d5b554e277d}{test\-Catches\-Cxx\-Exceptions\-In\-Fixture\-Destructor}
\item 
def \hyperlink{classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest_afd8e6fe37eb76af800212138fd3ffb27}{test\-Catches\-Cxx\-Exceptions\-In\-Set\-Up\-Test\-Case}
\item 
def \hyperlink{classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest_a2c885c7394e8890932e2946135f2c8a7}{test\-Catches\-Cxx\-Exceptions\-In\-Tear\-Down\-Test\-Case}
\item 
def \hyperlink{classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest_a244265aa2935ac2803cc16f21ace9d1e}{test\-Catches\-Cxx\-Exceptions\-In\-Set\-Up}
\item 
def \hyperlink{classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest_a5333d1dbcd9a372f5d61300775bc5305}{test\-Catches\-Cxx\-Exceptions\-In\-Tear\-Down}
\item 
def \hyperlink{classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest_ab0c384270ee0a7d906d7443378644619}{test\-Catches\-Cxx\-Exceptions\-In\-Test\-Body}
\item 
def \hyperlink{classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest_a35bedaabb28fea1fd611e99a9a6a14fe}{test\-Catches\-Non\-Std\-Cxx\-Exceptions}
\item 
def \hyperlink{classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest_a43283026c9019e592f3be2d01f04a492}{test\-Unhandled\-Cxx\-Exceptions\-Abort\-The\-Program}
\end{DoxyCompactItemize}


\subsection{\-Detailed \-Description}
\begin{DoxyVerb}Tests C++ exception-catching behavior.

   Tests in this test case verify that:
   * C++ exceptions are caught and logged as C++ (not SEH) exceptions
   * Exception thrown affect the remainder of the test work flow in the
     expected manner.
\end{DoxyVerb}
 

\-Definition at line 101 of file gtest\-\_\-catch\-\_\-exceptions\-\_\-test.\-py.



\subsection{\-Member \-Function \-Documentation}
\hypertarget{classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest_a5a885e791aafe476fdd5c27e892d03aa}{\index{gtest\-\_\-catch\-\_\-exceptions\-\_\-test\-::\-Catch\-Cxx\-Exceptions\-Test@{gtest\-\_\-catch\-\_\-exceptions\-\_\-test\-::\-Catch\-Cxx\-Exceptions\-Test}!test\-Catches\-Cxx\-Exceptions\-In\-Fixture\-Constructor@{test\-Catches\-Cxx\-Exceptions\-In\-Fixture\-Constructor}}
\index{test\-Catches\-Cxx\-Exceptions\-In\-Fixture\-Constructor@{test\-Catches\-Cxx\-Exceptions\-In\-Fixture\-Constructor}!gtest_catch_exceptions_test::CatchCxxExceptionsTest@{gtest\-\_\-catch\-\_\-exceptions\-\_\-test\-::\-Catch\-Cxx\-Exceptions\-Test}}
\subsubsection[{test\-Catches\-Cxx\-Exceptions\-In\-Fixture\-Constructor}]{\setlength{\rightskip}{0pt plus 5cm}def {\bf test\-Catches\-Cxx\-Exceptions\-In\-Fixture\-Constructor} (
\begin{DoxyParamCaption}
\item[{}]{self}
\end{DoxyParamCaption}
)}}\label{d4/d31/classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest_a5a885e791aafe476fdd5c27e892d03aa}


\-Definition at line 110 of file gtest\-\_\-catch\-\_\-exceptions\-\_\-test.\-py.


\begin{DoxyCode}
110 
111   def testCatchesCxxExceptionsInFixtureConstructor(self):
112     self.assert_('C++ exception with description '
113                  '"Standard C++ exception" thrown '
114                  'in the test fixture\'s constructor'
115                  in EX_BINARY_OUTPUT)
116     self.assert_('unexpected' not in EX_BINARY_OUTPUT,
117                  'This failure belongs in this test only if '
118                  '"CxxExceptionInConstructorTest" (no quotes) '
119                  'appears on the same line as words "called unexpectedly"')

\end{DoxyCode}
\hypertarget{classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest_a39d0315d69750ddc3d777d5b554e277d}{\index{gtest\-\_\-catch\-\_\-exceptions\-\_\-test\-::\-Catch\-Cxx\-Exceptions\-Test@{gtest\-\_\-catch\-\_\-exceptions\-\_\-test\-::\-Catch\-Cxx\-Exceptions\-Test}!test\-Catches\-Cxx\-Exceptions\-In\-Fixture\-Destructor@{test\-Catches\-Cxx\-Exceptions\-In\-Fixture\-Destructor}}
\index{test\-Catches\-Cxx\-Exceptions\-In\-Fixture\-Destructor@{test\-Catches\-Cxx\-Exceptions\-In\-Fixture\-Destructor}!gtest_catch_exceptions_test::CatchCxxExceptionsTest@{gtest\-\_\-catch\-\_\-exceptions\-\_\-test\-::\-Catch\-Cxx\-Exceptions\-Test}}
\subsubsection[{test\-Catches\-Cxx\-Exceptions\-In\-Fixture\-Destructor}]{\setlength{\rightskip}{0pt plus 5cm}def {\bf test\-Catches\-Cxx\-Exceptions\-In\-Fixture\-Destructor} (
\begin{DoxyParamCaption}
\item[{}]{self}
\end{DoxyParamCaption}
)}}\label{d4/d31/classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest_a39d0315d69750ddc3d777d5b554e277d}


\-Definition at line 120 of file gtest\-\_\-catch\-\_\-exceptions\-\_\-test.\-py.


\begin{DoxyCode}
120 
121   def testCatchesCxxExceptionsInFixtureDestructor(self):
122     self.assert_('C++ exception with description '
123                  '"Standard C++ exception" thrown '
124                  'in the test fixture\'s destructor'
125                  in EX_BINARY_OUTPUT)
126     self.assert_('CxxExceptionInDestructorTest::TearDownTestCase() '
127                  'called as expected.'
128                  in EX_BINARY_OUTPUT)

\end{DoxyCode}
\hypertarget{classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest_a244265aa2935ac2803cc16f21ace9d1e}{\index{gtest\-\_\-catch\-\_\-exceptions\-\_\-test\-::\-Catch\-Cxx\-Exceptions\-Test@{gtest\-\_\-catch\-\_\-exceptions\-\_\-test\-::\-Catch\-Cxx\-Exceptions\-Test}!test\-Catches\-Cxx\-Exceptions\-In\-Set\-Up@{test\-Catches\-Cxx\-Exceptions\-In\-Set\-Up}}
\index{test\-Catches\-Cxx\-Exceptions\-In\-Set\-Up@{test\-Catches\-Cxx\-Exceptions\-In\-Set\-Up}!gtest_catch_exceptions_test::CatchCxxExceptionsTest@{gtest\-\_\-catch\-\_\-exceptions\-\_\-test\-::\-Catch\-Cxx\-Exceptions\-Test}}
\subsubsection[{test\-Catches\-Cxx\-Exceptions\-In\-Set\-Up}]{\setlength{\rightskip}{0pt plus 5cm}def {\bf test\-Catches\-Cxx\-Exceptions\-In\-Set\-Up} (
\begin{DoxyParamCaption}
\item[{}]{self}
\end{DoxyParamCaption}
)}}\label{d4/d31/classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest_a244265aa2935ac2803cc16f21ace9d1e}


\-Definition at line 157 of file gtest\-\_\-catch\-\_\-exceptions\-\_\-test.\-py.


\begin{DoxyCode}
157 
158   def testCatchesCxxExceptionsInSetUp(self):
159     self.assert_('C++ exception with description "Standard C++ exception"'
160                  ' thrown in SetUp()'
161                  in EX_BINARY_OUTPUT)
162     self.assert_('CxxExceptionInSetUpTest::TearDownTestCase() '
163                  'called as expected.'
164                  in EX_BINARY_OUTPUT)
165     self.assert_('CxxExceptionInSetUpTest destructor '
166                  'called as expected.'
167                  in EX_BINARY_OUTPUT)
168     self.assert_('CxxExceptionInSetUpTest::TearDown() '
169                  'called as expected.'
170                  in EX_BINARY_OUTPUT)
171     self.assert_('unexpected' not in EX_BINARY_OUTPUT,
172                  'This failure belongs in this test only if '
173                  '"CxxExceptionInSetUpTest" (no quotes) '
174                  'appears on the same line as words "called unexpectedly"')

\end{DoxyCode}
\hypertarget{classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest_afd8e6fe37eb76af800212138fd3ffb27}{\index{gtest\-\_\-catch\-\_\-exceptions\-\_\-test\-::\-Catch\-Cxx\-Exceptions\-Test@{gtest\-\_\-catch\-\_\-exceptions\-\_\-test\-::\-Catch\-Cxx\-Exceptions\-Test}!test\-Catches\-Cxx\-Exceptions\-In\-Set\-Up\-Test\-Case@{test\-Catches\-Cxx\-Exceptions\-In\-Set\-Up\-Test\-Case}}
\index{test\-Catches\-Cxx\-Exceptions\-In\-Set\-Up\-Test\-Case@{test\-Catches\-Cxx\-Exceptions\-In\-Set\-Up\-Test\-Case}!gtest_catch_exceptions_test::CatchCxxExceptionsTest@{gtest\-\_\-catch\-\_\-exceptions\-\_\-test\-::\-Catch\-Cxx\-Exceptions\-Test}}
\subsubsection[{test\-Catches\-Cxx\-Exceptions\-In\-Set\-Up\-Test\-Case}]{\setlength{\rightskip}{0pt plus 5cm}def {\bf test\-Catches\-Cxx\-Exceptions\-In\-Set\-Up\-Test\-Case} (
\begin{DoxyParamCaption}
\item[{}]{self}
\end{DoxyParamCaption}
)}}\label{d4/d31/classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest_afd8e6fe37eb76af800212138fd3ffb27}


\-Definition at line 129 of file gtest\-\_\-catch\-\_\-exceptions\-\_\-test.\-py.


\begin{DoxyCode}
129 
130   def testCatchesCxxExceptionsInSetUpTestCase(self):
131     self.assert_('C++ exception with description "Standard C++ exception"'
132                  ' thrown in SetUpTestCase()'
133                  in EX_BINARY_OUTPUT)
134     self.assert_('CxxExceptionInConstructorTest::TearDownTestCase() '
135                  'called as expected.'
136                  in EX_BINARY_OUTPUT)
137     self.assert_('CxxExceptionInSetUpTestCaseTest constructor '
138                  'called as expected.'
139                  in EX_BINARY_OUTPUT)
140     self.assert_('CxxExceptionInSetUpTestCaseTest destructor '
141                  'called as expected.'
142                  in EX_BINARY_OUTPUT)
143     self.assert_('CxxExceptionInSetUpTestCaseTest::SetUp() '
144                  'called as expected.'
145                  in EX_BINARY_OUTPUT)
146     self.assert_('CxxExceptionInSetUpTestCaseTest::TearDown() '
147                  'called as expected.'
148                  in EX_BINARY_OUTPUT)
149     self.assert_('CxxExceptionInSetUpTestCaseTest test body '
150                  'called as expected.'
151                  in EX_BINARY_OUTPUT)

\end{DoxyCode}
\hypertarget{classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest_a5333d1dbcd9a372f5d61300775bc5305}{\index{gtest\-\_\-catch\-\_\-exceptions\-\_\-test\-::\-Catch\-Cxx\-Exceptions\-Test@{gtest\-\_\-catch\-\_\-exceptions\-\_\-test\-::\-Catch\-Cxx\-Exceptions\-Test}!test\-Catches\-Cxx\-Exceptions\-In\-Tear\-Down@{test\-Catches\-Cxx\-Exceptions\-In\-Tear\-Down}}
\index{test\-Catches\-Cxx\-Exceptions\-In\-Tear\-Down@{test\-Catches\-Cxx\-Exceptions\-In\-Tear\-Down}!gtest_catch_exceptions_test::CatchCxxExceptionsTest@{gtest\-\_\-catch\-\_\-exceptions\-\_\-test\-::\-Catch\-Cxx\-Exceptions\-Test}}
\subsubsection[{test\-Catches\-Cxx\-Exceptions\-In\-Tear\-Down}]{\setlength{\rightskip}{0pt plus 5cm}def {\bf test\-Catches\-Cxx\-Exceptions\-In\-Tear\-Down} (
\begin{DoxyParamCaption}
\item[{}]{self}
\end{DoxyParamCaption}
)}}\label{d4/d31/classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest_a5333d1dbcd9a372f5d61300775bc5305}


\-Definition at line 175 of file gtest\-\_\-catch\-\_\-exceptions\-\_\-test.\-py.


\begin{DoxyCode}
175 
176   def testCatchesCxxExceptionsInTearDown(self):
177     self.assert_('C++ exception with description "Standard C++ exception"'
178                  ' thrown in TearDown()'
179                  in EX_BINARY_OUTPUT)
180     self.assert_('CxxExceptionInTearDownTest::TearDownTestCase() '
181                  'called as expected.'
182                  in EX_BINARY_OUTPUT)
183     self.assert_('CxxExceptionInTearDownTest destructor '
184                  'called as expected.'
185                  in EX_BINARY_OUTPUT)

\end{DoxyCode}
\hypertarget{classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest_a2c885c7394e8890932e2946135f2c8a7}{\index{gtest\-\_\-catch\-\_\-exceptions\-\_\-test\-::\-Catch\-Cxx\-Exceptions\-Test@{gtest\-\_\-catch\-\_\-exceptions\-\_\-test\-::\-Catch\-Cxx\-Exceptions\-Test}!test\-Catches\-Cxx\-Exceptions\-In\-Tear\-Down\-Test\-Case@{test\-Catches\-Cxx\-Exceptions\-In\-Tear\-Down\-Test\-Case}}
\index{test\-Catches\-Cxx\-Exceptions\-In\-Tear\-Down\-Test\-Case@{test\-Catches\-Cxx\-Exceptions\-In\-Tear\-Down\-Test\-Case}!gtest_catch_exceptions_test::CatchCxxExceptionsTest@{gtest\-\_\-catch\-\_\-exceptions\-\_\-test\-::\-Catch\-Cxx\-Exceptions\-Test}}
\subsubsection[{test\-Catches\-Cxx\-Exceptions\-In\-Tear\-Down\-Test\-Case}]{\setlength{\rightskip}{0pt plus 5cm}def {\bf test\-Catches\-Cxx\-Exceptions\-In\-Tear\-Down\-Test\-Case} (
\begin{DoxyParamCaption}
\item[{}]{self}
\end{DoxyParamCaption}
)}}\label{d4/d31/classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest_a2c885c7394e8890932e2946135f2c8a7}


\-Definition at line 152 of file gtest\-\_\-catch\-\_\-exceptions\-\_\-test.\-py.


\begin{DoxyCode}
152 
153   def testCatchesCxxExceptionsInTearDownTestCase(self):
154     self.assert_('C++ exception with description "Standard C++ exception"'
155                  ' thrown in TearDownTestCase()'
156                  in EX_BINARY_OUTPUT)

\end{DoxyCode}
\hypertarget{classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest_ab0c384270ee0a7d906d7443378644619}{\index{gtest\-\_\-catch\-\_\-exceptions\-\_\-test\-::\-Catch\-Cxx\-Exceptions\-Test@{gtest\-\_\-catch\-\_\-exceptions\-\_\-test\-::\-Catch\-Cxx\-Exceptions\-Test}!test\-Catches\-Cxx\-Exceptions\-In\-Test\-Body@{test\-Catches\-Cxx\-Exceptions\-In\-Test\-Body}}
\index{test\-Catches\-Cxx\-Exceptions\-In\-Test\-Body@{test\-Catches\-Cxx\-Exceptions\-In\-Test\-Body}!gtest_catch_exceptions_test::CatchCxxExceptionsTest@{gtest\-\_\-catch\-\_\-exceptions\-\_\-test\-::\-Catch\-Cxx\-Exceptions\-Test}}
\subsubsection[{test\-Catches\-Cxx\-Exceptions\-In\-Test\-Body}]{\setlength{\rightskip}{0pt plus 5cm}def {\bf test\-Catches\-Cxx\-Exceptions\-In\-Test\-Body} (
\begin{DoxyParamCaption}
\item[{}]{self}
\end{DoxyParamCaption}
)}}\label{d4/d31/classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest_ab0c384270ee0a7d906d7443378644619}


\-Definition at line 186 of file gtest\-\_\-catch\-\_\-exceptions\-\_\-test.\-py.


\begin{DoxyCode}
186 
187   def testCatchesCxxExceptionsInTestBody(self):
188     self.assert_('C++ exception with description "Standard C++ exception"'
189                  ' thrown in the test body'
190                  in EX_BINARY_OUTPUT)
191     self.assert_('CxxExceptionInTestBodyTest::TearDownTestCase() '
192                  'called as expected.'
193                  in EX_BINARY_OUTPUT)
194     self.assert_('CxxExceptionInTestBodyTest destructor '
195                  'called as expected.'
196                  in EX_BINARY_OUTPUT)
197     self.assert_('CxxExceptionInTestBodyTest::TearDown() '
198                  'called as expected.'
199                  in EX_BINARY_OUTPUT)

\end{DoxyCode}
\hypertarget{classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest_a35bedaabb28fea1fd611e99a9a6a14fe}{\index{gtest\-\_\-catch\-\_\-exceptions\-\_\-test\-::\-Catch\-Cxx\-Exceptions\-Test@{gtest\-\_\-catch\-\_\-exceptions\-\_\-test\-::\-Catch\-Cxx\-Exceptions\-Test}!test\-Catches\-Non\-Std\-Cxx\-Exceptions@{test\-Catches\-Non\-Std\-Cxx\-Exceptions}}
\index{test\-Catches\-Non\-Std\-Cxx\-Exceptions@{test\-Catches\-Non\-Std\-Cxx\-Exceptions}!gtest_catch_exceptions_test::CatchCxxExceptionsTest@{gtest\-\_\-catch\-\_\-exceptions\-\_\-test\-::\-Catch\-Cxx\-Exceptions\-Test}}
\subsubsection[{test\-Catches\-Non\-Std\-Cxx\-Exceptions}]{\setlength{\rightskip}{0pt plus 5cm}def {\bf test\-Catches\-Non\-Std\-Cxx\-Exceptions} (
\begin{DoxyParamCaption}
\item[{}]{self}
\end{DoxyParamCaption}
)}}\label{d4/d31/classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest_a35bedaabb28fea1fd611e99a9a6a14fe}


\-Definition at line 200 of file gtest\-\_\-catch\-\_\-exceptions\-\_\-test.\-py.


\begin{DoxyCode}
200 
201   def testCatchesNonStdCxxExceptions(self):
202     self.assert_('Unknown C++ exception thrown in the test body'
203                  in EX_BINARY_OUTPUT)

\end{DoxyCode}
\hypertarget{classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest_a43283026c9019e592f3be2d01f04a492}{\index{gtest\-\_\-catch\-\_\-exceptions\-\_\-test\-::\-Catch\-Cxx\-Exceptions\-Test@{gtest\-\_\-catch\-\_\-exceptions\-\_\-test\-::\-Catch\-Cxx\-Exceptions\-Test}!test\-Unhandled\-Cxx\-Exceptions\-Abort\-The\-Program@{test\-Unhandled\-Cxx\-Exceptions\-Abort\-The\-Program}}
\index{test\-Unhandled\-Cxx\-Exceptions\-Abort\-The\-Program@{test\-Unhandled\-Cxx\-Exceptions\-Abort\-The\-Program}!gtest_catch_exceptions_test::CatchCxxExceptionsTest@{gtest\-\_\-catch\-\_\-exceptions\-\_\-test\-::\-Catch\-Cxx\-Exceptions\-Test}}
\subsubsection[{test\-Unhandled\-Cxx\-Exceptions\-Abort\-The\-Program}]{\setlength{\rightskip}{0pt plus 5cm}def {\bf test\-Unhandled\-Cxx\-Exceptions\-Abort\-The\-Program} (
\begin{DoxyParamCaption}
\item[{}]{self}
\end{DoxyParamCaption}
)}}\label{d4/d31/classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest_a43283026c9019e592f3be2d01f04a492}


\-Definition at line 204 of file gtest\-\_\-catch\-\_\-exceptions\-\_\-test.\-py.


\begin{DoxyCode}
204 
205   def testUnhandledCxxExceptionsAbortTheProgram(self):
206     # Filters out SEH exception tests on Windows. Unhandled SEH exceptions
207     # cause tests to show pop-up windows there.
208     FITLER_OUT_SEH_TESTS_FLAG = FILTER_FLAG + '=-*Seh*'
209     # By default, Google Test doesn't catch the exceptions.
210     uncaught_exceptions_ex_binary_output = gtest_test_utils.Subprocess(
211         [EX_EXE_PATH,
212          NO_CATCH_EXCEPTIONS_FLAG,
213          FITLER_OUT_SEH_TESTS_FLAG]).output
214 
215     self.assert_('Unhandled C++ exception terminating the program'
216                  in uncaught_exceptions_ex_binary_output)
217     self.assert_('unexpected' not in uncaught_exceptions_ex_binary_output)
218 

\end{DoxyCode}


\-The documentation for this class was generated from the following file\-:\begin{DoxyCompactItemize}
\item 
gtest-\/1.\-6.\-0/test/\hyperlink{gtest__catch__exceptions__test_8py}{gtest\-\_\-catch\-\_\-exceptions\-\_\-test.\-py}\end{DoxyCompactItemize}
